-- Sample data insertion script for DAILY_FLIGHTS table
-- You can run this directly in Snowflake's SQL interface

-- Clear existing data (optional)
-- TRUNCATE TABLE FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS;

-- Insert sample flights for today and the next few days
-- BOS to HYD flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0001', 750.50, '$750.50', 'BOS', 'HYD', CURRENT_TIMESTAMP(), DATEADD(hour, 18, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-1234', CURRENT_TIMESTAMP()),
('FL0002', 820.25, '$820.25', 'BOS', 'HYD', DATEADD(hour, 4, CURRENT_TIMESTAMP()), DATEADD(hour, 22, CURRENT_TIMESTAMP()), 'Emirates', 'EM-5678', CURRENT_TIMESTAMP()),
('FL0003', 695.00, '$695.00', 'BOS', 'HYD', DATEADD(hour, 8, CURRENT_TIMESTAMP()), DATEADD(hour, 26, CURRENT_TIMESTAMP()), 'Air India', 'AI-9012', CURRENT_TIMESTAMP()),
('FL0004', 910.75, '$910.75', 'BOS', 'HYD', DATEADD(hour, 12, CURRENT_TIMESTAMP()), DATEADD(hour, 30, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-3456', CURRENT_TIMESTAMP()),
('FL0005', 775.25, '$775.25', 'BOS', 'HYD', DATEADD(hour, 16, CURRENT_TIMESTAMP()), DATEADD(hour, 34, CURRENT_TIMESTAMP()), 'British Airways', 'BA-7890', CURRENT_TIMESTAMP());

-- HYD to BOS flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0006', 780.50, '$780.50', 'HYD', 'BOS', CURRENT_TIMESTAMP(), DATEADD(hour, 19, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-5678', CURRENT_TIMESTAMP()),
('FL0007', 840.25, '$840.25', 'HYD', 'BOS', DATEADD(hour, 5, CURRENT_TIMESTAMP()), DATEADD(hour, 23, CURRENT_TIMESTAMP()), 'Emirates', 'EM-9012', CURRENT_TIMESTAMP()),
('FL0008', 725.00, '$725.00', 'HYD', 'BOS', DATEADD(hour, 9, CURRENT_TIMESTAMP()), DATEADD(hour, 27, CURRENT_TIMESTAMP()), 'Air India', 'AI-3456', CURRENT_TIMESTAMP()),
('FL0009', 950.75, '$950.75', 'HYD', 'BOS', DATEADD(hour, 13, CURRENT_TIMESTAMP()), DATEADD(hour, 31, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-7890', CURRENT_TIMESTAMP()),
('FL0010', 795.25, '$795.25', 'HYD', 'BOS', DATEADD(hour, 17, CURRENT_TIMESTAMP()), DATEADD(hour, 35, CURRENT_TIMESTAMP()), 'British Airways', 'BA-1234', CURRENT_TIMESTAMP());

-- BOS to JFK flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0011', 250.50, '$250.50', 'BOS', 'JFK', CURRENT_TIMESTAMP(), DATEADD(hour, 1.5, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-2345', CURRENT_TIMESTAMP()),
('FL0012', 320.25, '$320.25', 'BOS', 'JFK', DATEADD(hour, 2, CURRENT_TIMESTAMP()), DATEADD(hour, 3.5, CURRENT_TIMESTAMP()), 'JetBlue Airways', 'JB-6789', CURRENT_TIMESTAMP()),
('FL0013', 195.00, '$195.00', 'BOS', 'JFK', DATEADD(hour, 4, CURRENT_TIMESTAMP()), DATEADD(hour, 5.5, CURRENT_TIMESTAMP()), 'American Airlines', 'AA-0123', CURRENT_TIMESTAMP()),
('FL0014', 310.75, '$310.75', 'BOS', 'JFK', DATEADD(hour, 6, CURRENT_TIMESTAMP()), DATEADD(hour, 7.5, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-4567', CURRENT_TIMESTAMP()),
('FL0015', 275.25, '$275.25', 'BOS', 'JFK', DATEADD(hour, 8, CURRENT_TIMESTAMP()), DATEADD(hour, 9.5, CURRENT_TIMESTAMP()), 'Southwest Airlines', 'SW-8901', CURRENT_TIMESTAMP());

-- JFK to BOS flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0016', 260.50, '$260.50', 'JFK', 'BOS', CURRENT_TIMESTAMP(), DATEADD(hour, 1.25, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-3456', CURRENT_TIMESTAMP()),
('FL0017', 340.25, '$340.25', 'JFK', 'BOS', DATEADD(hour, 2, CURRENT_TIMESTAMP()), DATEADD(hour, 3.25, CURRENT_TIMESTAMP()), 'JetBlue Airways', 'JB-7890', CURRENT_TIMESTAMP()),
('FL0018', 215.00, '$215.00', 'JFK', 'BOS', DATEADD(hour, 4, CURRENT_TIMESTAMP()), DATEADD(hour, 5.25, CURRENT_TIMESTAMP()), 'American Airlines', 'AA-1234', CURRENT_TIMESTAMP()),
('FL0019', 330.75, '$330.75', 'JFK', 'BOS', DATEADD(hour, 6, CURRENT_TIMESTAMP()), DATEADD(hour, 7.25, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-5678', CURRENT_TIMESTAMP()),
('FL0020', 295.25, '$295.25', 'JFK', 'BOS', DATEADD(hour, 8, CURRENT_TIMESTAMP()), DATEADD(hour, 9.25, CURRENT_TIMESTAMP()), 'Southwest Airlines', 'SW-9012', CURRENT_TIMESTAMP());

-- BOS to LAX flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0021', 450.50, '$450.50', 'BOS', 'LAX', CURRENT_TIMESTAMP(), DATEADD(hour, 6.5, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-4567', CURRENT_TIMESTAMP()),
('FL0022', 520.25, '$520.25', 'BOS', 'LAX', DATEADD(hour, 2, CURRENT_TIMESTAMP()), DATEADD(hour, 8.5, CURRENT_TIMESTAMP()), 'JetBlue Airways', 'JB-8901', CURRENT_TIMESTAMP()),
('FL0023', 395.00, '$395.00', 'BOS', 'LAX', DATEADD(hour, 4, CURRENT_TIMESTAMP()), DATEADD(hour, 10.5, CURRENT_TIMESTAMP()), 'American Airlines', 'AA-2345', CURRENT_TIMESTAMP()),
('FL0024', 510.75, '$510.75', 'BOS', 'LAX', DATEADD(hour, 6, CURRENT_TIMESTAMP()), DATEADD(hour, 12.5, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-6789', CURRENT_TIMESTAMP()),
('FL0025', 475.25, '$475.25', 'BOS', 'LAX', DATEADD(hour, 8, CURRENT_TIMESTAMP()), DATEADD(hour, 14.5, CURRENT_TIMESTAMP()), 'Southwest Airlines', 'SW-0123', CURRENT_TIMESTAMP());

-- LAX to BOS flights
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0026', 465.50, '$465.50', 'LAX', 'BOS', CURRENT_TIMESTAMP(), DATEADD(hour, 6.25, CURRENT_TIMESTAMP()), 'Delta Air Lines', 'DL-5678', CURRENT_TIMESTAMP()),
('FL0027', 535.25, '$535.25', 'LAX', 'BOS', DATEADD(hour, 2, CURRENT_TIMESTAMP()), DATEADD(hour, 8.25, CURRENT_TIMESTAMP()), 'JetBlue Airways', 'JB-9012', CURRENT_TIMESTAMP()),
('FL0028', 415.00, '$415.00', 'LAX', 'BOS', DATEADD(hour, 4, CURRENT_TIMESTAMP()), DATEADD(hour, 10.25, CURRENT_TIMESTAMP()), 'American Airlines', 'AA-3456', CURRENT_TIMESTAMP()),
('FL0029', 520.75, '$520.75', 'LAX', 'BOS', DATEADD(hour, 6, CURRENT_TIMESTAMP()), DATEADD(hour, 12.25, CURRENT_TIMESTAMP()), 'United Airlines', 'UA-7890', CURRENT_TIMESTAMP()),
('FL0030', 485.25, '$485.25', 'LAX', 'BOS', DATEADD(hour, 8, CURRENT_TIMESTAMP()), DATEADD(hour, 14.25, CURRENT_TIMESTAMP()), 'Southwest Airlines', 'SW-1234', CURRENT_TIMESTAMP());

-- Add flights for tomorrow (BOS to HYD)
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0031', 760.50, '$760.50', 'BOS', 'HYD', DATEADD(day, 1, CURRENT_TIMESTAMP()), DATEADD(hour, 18, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Delta Air Lines', 'DL-1235', CURRENT_TIMESTAMP()),
('FL0032', 830.25, '$830.25', 'BOS', 'HYD', DATEADD(hour, 4, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 22, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Emirates', 'EM-5679', CURRENT_TIMESTAMP()),
('FL0033', 705.00, '$705.00', 'BOS', 'HYD', DATEADD(hour, 8, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 26, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Air India', 'AI-9013', CURRENT_TIMESTAMP()),
('FL0034', 920.75, '$920.75', 'BOS', 'HYD', DATEADD(hour, 12, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 30, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'United Airlines', 'UA-3457', CURRENT_TIMESTAMP()),
('FL0035', 785.25, '$785.25', 'BOS', 'HYD', DATEADD(hour, 16, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 34, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'British Airways', 'BA-7891', CURRENT_TIMESTAMP());

-- Add flights for tomorrow (HYD to BOS)
INSERT INTO FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS 
(FLIGHT_ID, PRICE_RAW, PRICE_FORMATTED, ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME, ARRIVAL_TIME, AIRLINE_NAME, FLIGHT_NUMBER, LOAD_DATE)
VALUES
('FL0036', 790.50, '$790.50', 'HYD', 'BOS', DATEADD(day, 1, CURRENT_TIMESTAMP()), DATEADD(hour, 19, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Delta Air Lines', 'DL-5679', CURRENT_TIMESTAMP()),
('FL0037', 850.25, '$850.25', 'HYD', 'BOS', DATEADD(hour, 5, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 23, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Emirates', 'EM-9013', CURRENT_TIMESTAMP()),
('FL0038', 735.00, '$735.00', 'HYD', 'BOS', DATEADD(hour, 9, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 27, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'Air India', 'AI-3457', CURRENT_TIMESTAMP()),
('FL0039', 960.75, '$960.75', 'HYD', 'BOS', DATEADD(hour, 13, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 31, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'United Airlines', 'UA-7891', CURRENT_TIMESTAMP()),
('FL0040', 805.25, '$805.25', 'HYD', 'BOS', DATEADD(hour, 17, DATEADD(day, 1, CURRENT_TIMESTAMP())), DATEADD(hour, 35, DATEADD(day, 1, CURRENT_TIMESTAMP())), 'British Airways', 'BA-1235', CURRENT_TIMESTAMP());

-- Verify data was inserted
SELECT COUNT(*) FROM FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS;

-- View some sample data
SELECT * FROM FINAL_PROJECT.PUBLIC.DAILY_FLIGHTS LIMIT 10;